import {txrEditMainSlice} from "./slice";

const {
    setName,
    setCompany,
    setNode,
    setVideoConnection,
    setEncoder,
    setApplication,
    setInputFormat,
    setOutputType,
    setLatency,
    setVideoOutputIp,
    setAudioOutputIp,
    setOutputIp,
    setVideoOutputPort,
    setAudioOutputPort,
    setOutputPort,
    setTtl,
    setSDIDevice,
    addTxrDestination,
    deleteTxrDestination,
} = txrEditMainSlice.actions;

export {
    setName,
    setCompany,
    setNode,
    setVideoConnection,
    setEncoder,
    setApplication,
    setInputFormat,
    setOutputType,
    setLatency,
    setVideoOutputIp,
    setAudioOutputIp,
    setOutputIp,
    setVideoOutputPort,
    setAudioOutputPort,
    setOutputPort,
    setTtl,
    setSDIDevice,
    deleteTxrDestination,
    addTxrDestination,
};
