import {txrEditMainSlice} from "./slice";

const {
    setName,
    setCompany,
    setSourceIp,
    setTxNodeId,
    setRxNodeId,
    setSourcePort,
    setTxUseInterface,
    setTransmissionIp,
    setDestinationIp,
    setDestinationPort,
    setRxUseInterface,
    setTransmissionPort,
    setBufferHandler,
    setTTLPort,
    setDoubleTransmission,
    setOpenPortAt,
    toggleRxRunMonitor,
    setAppType,
} = txrEditMainSlice.actions;

export {
    setName,
    setCompany,
    setSourceIp,
    setTxNodeId,
    setRxNodeId,
    setSourcePort,
    setTxUseInterface,
    setTransmissionIp,
    setDestinationIp,
    setDestinationPort,
    setRxUseInterface,
    setTransmissionPort,
    setBufferHandler,
    setTTLPort,
    setDoubleTransmission,
    setOpenPortAt,
    toggleRxRunMonitor,
    setAppType,
};
