import {
    EChannelNavAppList,
    EDecryptionNavAppList,
    EEncryptionNavAppList,
    EFailoverNavAppList,
    EFilePlayerNavAppList,
    EHlsAnalyzerNavAppList,
    EHyperDeckNavAppList,
    EIpbeNavAppList,
    EMptsNavAppList,
    EMultiscreenNavAppList,
    ENxtLitePlayerNavAppList,
    EQFrameNavAppList,
    ESdiPlayerNavAppList,
    ESlateGeneratorNavAppList,
    ESptsNavAppList,
    ESrtNavAppList,
    EStandardsConversionNavAppList,
    ESupervisorNavAppList,
    ETeranexNavAppList,
    ETimeshiftingNavAppList,
    ETranscoder2NavAppList,
    ETranscoderNavAppList,
    ETsForwardNavAppList,
    ETxrNavAppList,
    INavApplicationState,
} from "./types";

export const applicationInitialState: INavApplicationState = {
    ipbe: {
        key: "ipbe",
        label: "SDI to IP Encoder",
        active: localStorage.getItem("ipbe") ? JSON.parse(localStorage.getItem("ipbe") as string) : true,
        permission: "",
        disabled: true,
        tabs: {
            manageIpbe: {
                active: true,
                disabled: true,
                permission: "",
                link: "/ipbes",
                key: "manageIpbe",
                label: EIpbeNavAppList.manageIpbe,
            },
            createIpbe: {
                disabled: true,
                active: true,
                permission: "",
                link: "/ipbe",
                key: "createIpbe",
                label: EIpbeNavAppList.createIpbe,
            },
        },
    },
    txr: {
        key: "txr",
        label: "Transfer",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageTxr: {
                active: true,
                disabled: true,
                permission: "",
                link: "/txrs",
                key: "manageTxr",
                label: ETxrNavAppList.manageTxr,
            },
            createTxr: {
                active: true,
                disabled: true,
                permission: "",
                link: "/txr",
                key: "createTxr",
                label: ETxrNavAppList.createTxr,
            },
            manageProxyServerForTxr6: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageProxyServerForTxr6",
                label: ETxrNavAppList.manageProxyServerForTxr6,
            },
        },
    },
    channel: {
        key: "channel",
        label: "Channel",
        permission: "",
        disabled: true,
        active: true,
        tabs: {
            manageChannels: {
                disabled: true,
                active: true,
                permission: "",
                link: "",
                key: "manageChannels",
                label: EChannelNavAppList.manageChannels,
            },
            manageTemplates: {
                disabled: true,
                active: true,
                permission: "",
                link: "",
                key: "manageTemplates",
                label: EChannelNavAppList.manageTemplates,
            },
            manageLogotypes: {
                disabled: true,
                active: true,
                permission: "",
                link: "",
                key: "manageLogotypes",
                label: EChannelNavAppList.manageLogotypes,
            },
            appSchedule: {
                disabled: true,
                active: true,
                permission: "",
                link: "",
                key: "appSchedule",
                label: EChannelNavAppList.appSchedule,
            },
        },
    },
    transcoder2: {
        key: "transcoder2",
        label: "Transcoder 2.0",
        permission: "",
        disabled: true,
        active: true,
        tabs: {
            manageTranscoders2: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageTranscoders2",
                label: ETranscoder2NavAppList.manageTranscoders2,
            },
            createTranscoder2: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createTranscoder2",
                label: ETranscoder2NavAppList.createTranscoder2,
            },
            dashboard: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "dashboard",
                label: ETranscoder2NavAppList.dashboard,
            },
            manageEncoderTemplates: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageEncoderTemplates",
                label: ETranscoder2NavAppList.manageEncoderTemplates,
            },
        },
    },
    transcoder: {
        key: "transcoder",
        label: "Transcoder",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageTranscoders: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageTranscoders",
                label: ETranscoderNavAppList.manageTranscoders,
            },
            manageOutputServers: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageOutputServers",
                label: ETranscoderNavAppList.manageOutputServers,
            },
            channelListCsv: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "channelListCsv",
                label: ETranscoderNavAppList.channelListCsv,
            },
        },
    },
    standardsConversion: {
        key: "standardsConversion",
        label: "Standards conversion",
        active: true,
        disabled: true,
        permission: "",
        tabs: {
            manageConverter: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageConverter",
                label: EStandardsConversionNavAppList.manageConverter,
            },
            createNewConverter: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createNewConverter",
                label: EStandardsConversionNavAppList.createNewConverter,
            },
            converterDashboard: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "converterDashboard",
                label: EStandardsConversionNavAppList.converterDashboard,
            },
        },
    },
    slateGenerator: {
        key: "slateGenerator",
        label: "Slate Generator",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageSlateGenerators: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSlateGenerators",
                label: ESlateGeneratorNavAppList.manageSlateGenerators,
            },
            createSlateGenerator: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createSlateGenerator",
                label: ESlateGeneratorNavAppList.createSlateGenerator,
            },
        },
    },
    sdiPlayer: {
        key: "sdiPlayer",
        label: "SDI Player",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageSdiplayers: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSdiplayers",
                label: ESdiPlayerNavAppList.manageSdiplayers,
            },
            createSdiPlayer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createSdiPlayer",
                label: ESdiPlayerNavAppList.createSdiPlayer,
            },
        },
    },
    srt: {
        key: "srt",
        label: "SRT",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageSrt: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSrt",
                label: ESrtNavAppList.manageSrt,
            },
            createSrt: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createSrt",
                label: ESrtNavAppList.createSrt,
            },
        },
    },
    spts: {
        key: "spts",
        label: "SPTS",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageSpts: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSpts",
                label: ESptsNavAppList.manageSpts,
            },
            createSpts: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createSpts",
                label: ESptsNavAppList.createSpts,
            },
        },
    },
    mpts: {
        key: "mpts",
        label: "MPTS",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageMpts: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageMpts",
                label: EMptsNavAppList.manageMpts,
            },
            createMpts: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createMpts",
                label: EMptsNavAppList.createMpts,
            },
        },
    },
    supervisor: {
        key: "supervisor",
        label: "Supervisor",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageSupervisors: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSupervisors",
                label: ESupervisorNavAppList.manageSupervisors,
            },
            createSupervisor: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createSupervisor",
                label: ESupervisorNavAppList.createSupervisor,
            },
            manageSupervisorApplications: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageSupervisorApplications",
                label: ESupervisorNavAppList.manageSupervisorApplications,
            },
        },
    },
    teranex: {
        key: "teranex",
        label: "Teranex",
        permission: "",
        disabled: true,
        active: true,
        tabs: {
            manageTeranexes: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageTeranexes",
                label: ETeranexNavAppList.manageTeranexes,
            },
            createTeranex: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createTeranex",
                label: ETeranexNavAppList.createTeranex,
            },
        },
    },
    timeshifting: {
        key: "timeshifting",
        label: "Timeshifting",
        permission: "",
        disabled: true,
        active: true,
        tabs: {
            manageTimeshifting: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageTimeshifting",
                label: ETimeshiftingNavAppList.manageTimeshifting,
            },
            createTimeshifting: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createTimeshifting",
                label: ETimeshiftingNavAppList.createTimeshifting,
            },
        },
    },
    failover: {
        key: "failover",
        label: "Failover",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageFailover: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageFailover",
                label: EFailoverNavAppList.manageFailover,
            },
            createFailover: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createFailover",
                label: EFailoverNavAppList.createFailover,
            },
        },
    },
    tsForward: {
        key: "tsForward",
        label: "TSForward",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageTsForward: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageTsForward",
                label: ETsForwardNavAppList.manageTsForward,
            },
            createTsForward: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createTsForward",
                label: ETsForwardNavAppList.createTsForward,
            },
        },
    },
    multiscreen: {
        key: "multiscreen",
        label: "Multiscreen",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageMultiscreens: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageMultiscreens",
                label: EMultiscreenNavAppList.manageMultiscreens,
            },
            createMultiscreen: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createMultiscreen",
                label: EMultiscreenNavAppList.createMultiscreen,
            },
        },
    },
    qFrame: {
        key: "qFrame",
        label: "QFrame",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageQFrame: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageQFrame",
                label: EQFrameNavAppList.manageQFrame,
            },
            createQFrame: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createQFrame",
                label: EQFrameNavAppList.createQFrame,
            },
        },
    },
    encryption: {
        key: "encryption",
        label: "Encryption",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageEncryptions: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageEncryptions",
                label: EEncryptionNavAppList.manageEncryptions,
            },
            createEncryption: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createEncryption",
                label: EEncryptionNavAppList.createEncryption,
            },
        },
    },
    decryption: {
        key: "decryption",
        label: "Decryption",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageDecryption: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageDecryption",
                label: EDecryptionNavAppList.manageDecryption,
            },
            createDecryption: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createDecryption",
                label: EDecryptionNavAppList.createDecryption,
            },
        },
    },
    nxtLitePlayer: {
        key: "nxtLitePlayer",
        label: "NxtLite Player",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageNxtLitePlayers: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageNxtLitePlayers",
                label: ENxtLitePlayerNavAppList.manageNxtLitePlayers,
            },
            createNxtLitePlayer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createNxtLitePlayer",
                label: ENxtLitePlayerNavAppList.createNxtLitePlayer,
            },
        },
    },
    filePlayer: {
        key: "filePlayer",
        label: "File Player",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageFilePlayer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageFilePlayer",
                label: EFilePlayerNavAppList.manageFilePlayer,
            },
            createFilePlayer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createFilePlayer",
                label: EFilePlayerNavAppList.createFilePlayer,
            },
        },
    },
    hyperDeck: {
        key: "hyperDeck",
        label: "HyperDeck",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageHyperDecks: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageHyperDecks",
                label: EHyperDeckNavAppList.manageHyperDecks,
            },
            createHyperDeck: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createHyperDeck",
                label: EHyperDeckNavAppList.createHyperDeck,
            },
        },
    },
    hlsAnalyzer: {
        key: "hlsAnalyzer",
        label: "HLS Analyzer",
        permission: "",
        active: true,
        disabled: true,
        tabs: {
            manageHlsAnalyzer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "manageHlsAnalyzer",
                label: EHlsAnalyzerNavAppList.manageHlsAnalyzer,
            },
            createHlsAnalyzer: {
                active: true,
                disabled: true,
                permission: "",
                link: "",
                key: "createHlsAnalyzer",
                label: EHlsAnalyzerNavAppList.createHlsAnalyzer,
            },
        },
    },
};
