import {activeNavTabState} from "../utils";
import {
    EApNavProjectList,
    EApOccasionalUseNavProjectList,
    EApTestsNavProjectList,
    ECommercialDetectionNavProjectList,
    EExportWebStreamNavProjectList,
    EHlsPacketizersNavProjectList,
    EMagsNavProjectList,
    EMediaNavProjectList,
    EMobileMultiviewNavProjectList,
    ENextomeetNavProjectList,
    EProjectsNavProjectList,
    ERaspberryNavProjectList,
    EVideoHubNavProjectList,
    EWebPlayerNavProjectList,
    INavProjectState,
} from "./types";

export const projectsInitialState: INavProjectState = {
    projects: {
        id: 1,
        key: "projects",
        label: "Projects",
        permission: "",
        active: activeNavTabState("projects"),
        disabled: true,
        tabs: {
            crtcChannelsLogger: {
                id: 8,
                active: activeNavTabState("crtcChannelsLogger"),
                disabled: true,
                permission: "",
                link: "",
                key: "crtcChannelsLogger",
                label: EProjectsNavProjectList.crtcChannelsLogger,
            },
            addb: {
                id: 4,
                active: activeNavTabState("addb"),
                disabled: true,
                permission: "",
                link: "",
                key: "addb",
                label: EProjectsNavProjectList.addb,
            },
            crm: {
                id: 3,
                active: activeNavTabState("crm"),
                disabled: true,
                permission: "",
                link: "",
                key: "crm",
                label: EProjectsNavProjectList.crm,
            },
            ingest: {
                id: 2,
                active: activeNavTabState("ingest"),
                disabled: true,
                permission: "",
                link: "",
                key: "ingest",
                label: EProjectsNavProjectList.ingest,
            },
            mailing: {
                id: 1,
                active: activeNavTabState("mailing"),
                disabled: true,
                permission: "",
                link: "",
                key: "mailing",
                label: EProjectsNavProjectList.mailing,
            },
            nxtMeet1: {
                id: 10,
                active: activeNavTabState("nxtMeet1"),
                disabled: true,
                permission: "",
                link: "",
                key: "nxtMeet1",
                label: EProjectsNavProjectList.nxtMeet1,
            },
            ptzCameraTest: {
                id: 7,
                active: activeNavTabState("ptzCameraTest"),
                disabled: true,
                permission: "",
                link: "",
                key: "ptzCameraTest",
                label: EProjectsNavProjectList.ptzCameraTest,
            },
            streaming: {
                id: 6,
                active: activeNavTabState("streaming"),
                disabled: true,
                permission: "",
                link: "",
                key: "streaming",
                label: EProjectsNavProjectList.streaming,
            },
            transcodingCluster: {
                id: 5,
                active: activeNavTabState("transcodingCluster"),
                disabled: true,
                permission: "",
                link: "",
                key: "transcodingCluster",
                label: EProjectsNavProjectList.transcodingCluster,
            },
            voiceDetection: {
                id: 9,
                active: activeNavTabState("voiceDetection"),
                disabled: true,
                permission: "",
                link: "",
                key: "voiceDetection",
                label: EProjectsNavProjectList.voiceDetection,
            },
        },
    },
    webPlayer: {
        id: 2,

        key: "webPlayer",
        label: "Web Player",
        permission: "",
        active: activeNavTabState("webPlayer"),
        disabled: true,
        tabs: {
            projectManageWebPlayers: {
                active: activeNavTabState("projectManageWebPlayers"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageWebPlayers",
                label: EWebPlayerNavProjectList.projectManageWebPlayers,
            },
            projectCreateWebPlayer: {
                active: activeNavTabState("projectCreateWebPlayer"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateWebPlayer",
                label: EWebPlayerNavProjectList.projectCreateWebPlayer,
            },
            projectMonitoringSecurityCameras: {
                active: activeNavTabState("projectMonitoringSecurityCameras"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectMonitoringSecurityCameras",
                label: EWebPlayerNavProjectList.projectMonitoringSecurityCameras,
            },
        },
    },
    apOccasionalUse: {
        id: 3,

        key: "apOccasionalUse",
        label: "AP Occasional Use",
        permission: "",
        active: activeNavTabState("apOccasionalUse"),
        disabled: true,
        tabs: {
            projectApOccasionalUseSettings: {
                active: activeNavTabState("projectApOccasionalUseSettings"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectApOccasionalUseSettings",
                label: EApOccasionalUseNavProjectList.projectApOccasionalUseSettings,
            },
            projectManageAPOccasionalUse: {
                active: activeNavTabState("projectManageAPOccasionalUse"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageAPOccasionalUse",
                label: EApOccasionalUseNavProjectList.projectManageAPOccasionalUse,
            },
        },
    },
    ap: {
        id: 4,
        key: "ap",
        label: "AP",
        permission: "",
        active: activeNavTabState("ap"),
        disabled: true,
        tabs: {
            projectApAltDelivery: {
                id: 9,
                active: activeNavTabState("projectApAltDelivery"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectApAltDelivery",
                label: EApNavProjectList.projectApAltDelivery,
            },
            projectApClients: {
                id: 3,
                active: activeNavTabState("projectApClients"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectApClients",
                label: EApNavProjectList.projectApClients,
            },
            projectApDashboard: {
                id: 1,
                active: activeNavTabState("projectApDashboard"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectApDashboard",
                label: EApNavProjectList.projectApDashboard,
            },
            projectCdnProfileChecker: {
                id: 11,
                active: activeNavTabState("projectCdnProfileChecker"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCdnProfileChecker",
                label: EApNavProjectList.projectCdnProfileChecker,
            },
            projectCdnReport: {
                id: 2,
                active: activeNavTabState("projectCdnReport"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCdnReport",
                label: EApNavProjectList.projectCdnReport,
            },
            projectGenerateInvoice: {
                id: 13,
                active: activeNavTabState("projectGenerateInvoice"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectGenerateInvoice",
                label: EApNavProjectList.projectGenerateInvoice,
            },
            projectManagePlayoutItems: {
                id: 6,
                active: activeNavTabState("projectManagePlayoutItems"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManagePlayoutItems",
                label: EApNavProjectList.projectManagePlayoutItems,
            },
            projectManageReplays: {
                id: 5,
                active: activeNavTabState("projectManageReplays"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageReplays",
                label: EApNavProjectList.projectManageReplays,
            },
            projectMediaServers: {
                id: 10,
                active: activeNavTabState("projectMediaServers"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectMediaServers",
                label: EApNavProjectList.projectMediaServers,
            },
            projectPricingSettings: {
                id: 12,
                active: activeNavTabState("projectPricingSettings"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectPricingSettings",
                label: EApNavProjectList.projectPricingSettings,
            },
            projectSdiPlayoutErrorsLog: {
                id: 7,
                active: activeNavTabState("projectSdiPlayoutErrorsLog"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectSdiPlayoutErrorsLog",
                label: EApNavProjectList.projectSdiPlayoutErrorsLog,
            },
            projectSlateDetails: {
                id: 8,
                active: activeNavTabState("projectSlateDetails"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectSlateDetails",
                label: EApNavProjectList.projectSlateDetails,
            },
            projectViewAllEndpoints: {
                id: 4,
                active: activeNavTabState("projectViewAllEndpoints"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectViewAllEndpoints",
                label: EApNavProjectList.projectViewAllEndpoints,
            },
        },
    },
    apTests: {
        id: 5,

        key: "apTests",
        label: "AP Tests",
        permission: "",
        active: activeNavTabState("apTests"),
        disabled: true,
        tabs: {
            projectManageApCdnLinks: {
                id: 3,
                active: activeNavTabState("projectManageApCdnLinks"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageApCdnLinks",
                label: EApTestsNavProjectList.projectManageApCdnLinks,
            },
            projectTestApCdn: {
                id: 2,
                active: activeNavTabState("projectTestApCdn"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectTestApCdn",
                label: EApTestsNavProjectList.projectTestApCdn,
            },
            projectViewApStreams: {
                id: 1,
                active: activeNavTabState("projectViewApStreams"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectViewApStreams",
                label: EApTestsNavProjectList.projectViewApStreams,
            },
        },
    },
    raspberry: {
        id: 6,

        key: "raspberry",
        label: "Raspberry",
        permission: "",
        active: activeNavTabState("raspberry"),
        disabled: true,
        tabs: {
            projectManageRaspberry: {
                active: activeNavTabState("projectManageRaspberry"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageRaspberry",
                label: ERaspberryNavProjectList.projectManageRaspberry,
            },
            projectCreateRaspberry: {
                active: activeNavTabState("projectCreateRaspberry"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateRaspberry",
                label: ERaspberryNavProjectList.projectCreateRaspberry,
            },
        },
    },
    mags: {
        id: 7,

        key: "mags",
        label: "MAGS",
        permission: "",
        active: activeNavTabState("mags"),
        disabled: true,
        tabs: {
            projectManageMags: {
                active: activeNavTabState("projectManageMags"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageMags",
                label: EMagsNavProjectList.projectManageMags,
            },
            projectCreateMag: {
                active: activeNavTabState("projectCreateMag"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateMag",
                label: EMagsNavProjectList.projectCreateMag,
            },
        },
    },
    commercialDetection: {
        id: 8,

        key: "commercialDetection",
        label: "Commercial Detection",
        permission: "",
        active: activeNavTabState("commercialDetection"),
        disabled: true,
        tabs: {
            projectAdvLibrary: {
                id: 3,
                active: activeNavTabState("projectAdvLibrary"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectAdvLibrary",
                label: ECommercialDetectionNavProjectList.projectAdvLibrary,
            },
            projectBlackDetectLog: {
                id: 4,
                active: activeNavTabState("projectBlackDetectLog"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectBlackDetectLog",
                label: ECommercialDetectionNavProjectList.projectBlackDetectLog,
            },
            projectLogoDetection: {
                id: 5,
                active: activeNavTabState("projectLogoDetection"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectLogoDetection",
                label: ECommercialDetectionNavProjectList.projectLogoDetection,
            },
            projectManageChannels: {
                id: 1,
                active: activeNavTabState("projectManageChannels"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageChannels",
                label: ECommercialDetectionNavProjectList.projectManageChannels,
            },
            projectReviewCommercials: {
                id: 2,
                active: activeNavTabState("projectReviewCommercials"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectReviewCommercials",
                label: ECommercialDetectionNavProjectList.projectReviewCommercials,
            },
            projectScteLogger: {
                id: 6,
                active: activeNavTabState("projectScteLogger"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectScteLogger",
                label: ECommercialDetectionNavProjectList.projectScteLogger,
            },
        },
    },
    exportWebStream: {
        id: 9,

        key: "exportWebStream",
        label: "Export Web Stream",
        permission: "",
        active: activeNavTabState("exportWebStream"),
        disabled: true,
        tabs: {
            projectManageEmbedLink: {
                active: activeNavTabState("projectManageEmbedLink"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageEmbedLink",
                label: EExportWebStreamNavProjectList.projectManageEmbedLink,
            },
            projectCreateEmbedLink: {
                active: activeNavTabState("projectCreateEmbedLink"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateEmbedLink",
                label: EExportWebStreamNavProjectList.projectCreateEmbedLink,
            },
        },
    },
    media: {
        id: 10,

        key: "media",
        label: "Media",
        permission: "",
        active: activeNavTabState("media"),
        disabled: true,
        tabs: {
            projectMediaServers: {
                active: activeNavTabState("projectMediaServers"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectMediaServers",
                label: EMediaNavProjectList.projectMediaServers,
            },
            projectMpegtsInputOutput: {
                active: activeNavTabState("projectMpegtsInputOutput"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectMpegtsInputOutput",
                label: EMediaNavProjectList.projectMpegtsInputOutput,
            },
            projectRepublishing: {
                active: activeNavTabState("projectRepublishing"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectRepublishing",
                label: EMediaNavProjectList.projectRepublishing,
            },
        },
    },
    mobileMultiview: {
        id: 11,

        key: "mobileMultiview",
        label: "Mobile multiview",
        permission: "",
        active: activeNavTabState("mobileMultiview"),
        disabled: true,
        tabs: {
            projectAddMultiview: {
                id: 2,
                active: activeNavTabState("projectAddMultiview"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectAddMultiview",
                label: EMobileMultiviewNavProjectList.projectAddMultiview,
            },
            projectManageMultiview: {
                id: 1,
                active: activeNavTabState("projectManageMultiview"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageMultiview",
                label: EMobileMultiviewNavProjectList.projectManageMultiview,
            },
        },
    },
    videoHub: {
        id: 12,

        key: "videoHub",
        label: "VideoHub",
        permission: "",
        active: activeNavTabState("videoHub"),
        disabled: true,
        tabs: {
            projectManageVideoHubs: {
                active: activeNavTabState("projectManageVideoHubs"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectManageVideoHubs",
                label: EVideoHubNavProjectList.projectManageVideoHubs,
            },
            projectCreateVideoHub: {
                active: activeNavTabState("projectCreateVideoHub"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateVideoHub",
                label: EVideoHubNavProjectList.projectCreateVideoHub,
            },
        },
    },
    hlsPacketizers: {
        id: 13,

        key: "hlsPacketizers",
        label: "Hls Packetizers",
        permission: "",
        active: activeNavTabState("hlsPacketizers"),
        disabled: true,
        tabs: {
            projectHlsPacketizers: {
                active: activeNavTabState("projectHlsPacketizers"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectHlsPacketizers",
                label: EHlsPacketizersNavProjectList.projectHlsPacketizers,
            },
            projectCreateHlsPacketizer: {
                active: activeNavTabState("projectCreateHlsPacketizer"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCreateHlsPacketizer",
                label: EHlsPacketizersNavProjectList.projectCreateHlsPacketizer,
            },
        },
    },
    nextomeet: {
        id: 14,

        active: activeNavTabState("nextomeet"),
        disabled: true,
        key: "nextomeet",
        label: "Nextomeet",
        permission: "",
        tabs: {
            projectCalendar: {
                id: 4,
                active: activeNavTabState("projectCalendar"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectCalendar",
                label: ENextomeetNavProjectList.projectCalendar,
            },
            projectNextomeetRooms: {
                id: 2,
                active: activeNavTabState("projectNextomeetRooms"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectNextomeetRooms",
                label: ENextomeetNavProjectList.projectNextomeetRooms,
            },
            projectNextomeetServers: {
                id: 1,
                active: activeNavTabState("projectNextomeetServers"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectNextomeetServers",
                label: ENextomeetNavProjectList.projectNextomeetServers,
            },
            projectSdiMonitoring: {
                id: 3,
                active: activeNavTabState("projectSdiMonitoring"),
                disabled: true,
                permission: "",
                link: "",
                key: "projectSdiMonitoring",
                label: ENextomeetNavProjectList.projectSdiMonitoring,
            },
        },
    },
};
