import {ipbeEditVideoEncoderSlice} from "./slice";

const {
    changeVideoEncoder,
    changePreset,
    changeProfile,
    changeLevel,
    changeVBitrate,
    changeVBVMaxrate,
    changeVBVBufsize,
    changeAspectRatio,
    changeKeyint,
    changeBframes,
    changeMaxRefs,
    changeLookahead,
    changeOpenGop,
    changeCbr,
    changeIntraRefresh,
    changeBFrameAdaptive,
    changeScenecutThreshold,
    changeInterlaced,
    changeThread,
} = ipbeEditVideoEncoderSlice.actions;

export {
    changeVideoEncoder,
    changePreset,
    changeProfile,
    changeLevel,
    changeVBitrate,
    changeVBVMaxrate,
    changeVBVBufsize,
    changeAspectRatio,
    changeKeyint,
    changeBframes,
    changeMaxRefs,
    changeLookahead,
    changeOpenGop,
    changeCbr,
    changeIntraRefresh,
    changeBFrameAdaptive,
    changeScenecutThreshold,
    changeInterlaced,
    changeThread,
};
