import {ipbeEditVideoEncoderSlice} from "./slice";

const {
    setVideoEncoder,
    setPreset,
    setProfile,
    setLevel,
    setVBitrate,
    setVBVMaxrate,
    setVBVBufsize,
    setAspectRatio,
    setKeyint,
    setBframes,
    setMaxRefs,
    setLookahead,
    setOpenGop,
    setCbr,
    setIntraRefresh,
    setBFrameAdaptive,
    setScenecutThreshold,
    setInterlaced,
    setThread,
} = ipbeEditVideoEncoderSlice.actions;

export {
    setVideoEncoder,
    setPreset,
    setProfile,
    setLevel,
    setVBitrate,
    setVBVMaxrate,
    setVBVBufsize,
    setAspectRatio,
    setKeyint,
    setBframes,
    setMaxRefs,
    setLookahead,
    setOpenGop,
    setCbr,
    setIntraRefresh,
    setBFrameAdaptive,
    setScenecutThreshold,
    setInterlaced,
    setThread,
};
