import {ipbeEditMainSlice} from "./slice";

const {
    setName,
    setCompany,
    setNode,
    setVideoConnection,
    setEncoder,
    setApplication,
    setInputFormat,
    setOutputType,
    setLatency,
    setVideoOutputIp,
    setAudioOutputIp,
    setOutputIp,
    setVideoOutputPort,
    setAudioOutputPort,
    setOutputPort,
    setTtl,
    setSDIDevice,
    addIpbeDestination,
    deleteIpbeDestination,
} = ipbeEditMainSlice.actions;

export {
    setName,
    setCompany,
    setNode,
    setVideoConnection,
    setEncoder,
    setApplication,
    setInputFormat,
    setOutputType,
    setLatency,
    setVideoOutputIp,
    setAudioOutputIp,
    setOutputIp,
    setVideoOutputPort,
    setAudioOutputPort,
    setOutputPort,
    setTtl,
    setSDIDevice,
    deleteIpbeDestination,
    addIpbeDestination,
};
