import {activeNavTabState} from "../utils";
import {ENodeNavAppList, INavNodeState} from "./types";

export const nodeInitialState: INavNodeState = {
    nodeCreateLocation: {
        active: activeNavTabState("nodeCreateLocation"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeCreateLocation",
        label: ENodeNavAppList.nodeCreateLocation,
    },
    nodeCreateNode: {
        active: activeNavTabState("nodeCreateNode"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeCreateNode",
        label: ENodeNavAppList.nodeCreateNode,
    },
    nodeManageLocations: {
        active: activeNavTabState("nodeManageLocations"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeManageLocations",
        label: ENodeNavAppList.nodeManageLocations,
    },
    nodeManageNodes: {
        active: activeNavTabState("nodeManageNodes"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeManageNodes",
        label: ENodeNavAppList.nodeManageNodes,
    },
    nodeOfflineNodes: {
        active: activeNavTabState("nodeOfflineNodes"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeOfflineNodes",
        label: ENodeNavAppList.nodeOfflineNodes,
    },
    nodeOurWorld: {
        active: activeNavTabState("nodeOurWorld"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeOurWorld",
        label: ENodeNavAppList.nodeOurWorld,
    },
    nodeOutdatedAppController: {
        active: activeNavTabState("nodeOutdatedAppController"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeOutdatedAppController",
        label: ENodeNavAppList.nodeOutdatedAppController,
    },
    nodeOutdatedController: {
        active: activeNavTabState("nodeOutdatedController"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeOutdatedController",
        label: ENodeNavAppList.nodeOutdatedController,
    },
    nodeStagingZone: {
        active: activeNavTabState("nodeStagingZone"),
        disabled: true,
        permission: "",
        link: "",
        key: "nodeStagingZone",
        label: ENodeNavAppList.nodeStagingZone,
    },
};
