import {activeNavTabState} from "../utils";
import {
    EAdReplacerNavAppList,
    EFastSyncNavAppList,
    EIngestNavAppList,
    EMamNavAppList,
    EPlayout2NavAppList,
    EPlayoutNavAppList,
    INavPlayoutState,
} from "./types";

export const playoutInitialState: INavPlayoutState = {
    playout: {
        id: 1,
        key: "playout",
        label: "Playout",
        permission: "",
        active: activeNavTabState("playout"),
        disabled: true,
        tabs: {
            playoutManageChannels: {
                active: activeNavTabState("playoutManageChannels"),
                disabled: true,
                permission: "",
                link: "",
                key: "playoutManageChannels",
                label: EPlayoutNavAppList.playoutManageChannels,
            },
            playoutCreateChannel: {
                active: activeNavTabState("playoutCreateChannel"),
                disabled: true,
                permission: "",
                link: "",
                key: "playoutCreateChannel",
                label: EPlayoutNavAppList.playoutCreateChannel,
            },
            playoutLiveSources: {
                active: activeNavTabState("playoutLiveSources"),
                disabled: true,
                permission: "",
                link: "",
                key: "playoutLiveSources",
                label: EPlayoutNavAppList.playoutLiveSources,
            },
            playoutManageLogo: {
                active: activeNavTabState("playoutManageLogo"),
                disabled: true,
                permission: "",
                link: "",
                key: "playoutManageLogo",
                label: EPlayoutNavAppList.playoutManageLogo,
            },
            playoutDashboard: {
                active: activeNavTabState("playoutDashboard"),
                disabled: true,
                permission: "",
                link: "",
                key: "playoutDashboard",
                label: EPlayoutNavAppList.playoutDashboard,
            },
        },
    },
    playout2: {
        id: 2,

        key: "playout2",
        label: "Playout 2.0",
        permission: "",
        active: activeNavTabState("playout2"),
        disabled: true,
        tabs: {
            playout2ManageChannels: {
                active: activeNavTabState("playout2ManageChannels"),
                disabled: true,
                permission: "",
                link: "",
                key: "playout2ManageChannels",
                label: EPlayout2NavAppList.playout2ManageChannels,
            },
            playout2ManagePlaylists: {
                active: activeNavTabState("playout2ManagePlaylists"),
                disabled: true,
                permission: "",
                link: "",
                key: "playout2ManagePlaylists",
                label: EPlayout2NavAppList.playout2ManagePlaylists,
            },
            playout2MediaLibrary: {
                active: activeNavTabState("playout2MediaLibrary"),
                disabled: true,
                permission: "",
                link: "",
                key: "playout2MediaLibrary",
                label: EPlayout2NavAppList.playout2MediaLibrary,
            },
            playout2LiveSources: {
                active: activeNavTabState("playout2LiveSources"),
                disabled: true,
                permission: "",
                link: "",
                key: "playout2LiveSources",
                label: EPlayout2NavAppList.playout2LiveSources,
            },
            playout2LivePlayoutMonitor: {
                active: activeNavTabState("playout2LivePlayoutMonitor"),
                disabled: true,
                permission: "",
                link: "",
                key: "playout2LivePlayoutMonitor",
                label: EPlayout2NavAppList.playout2LivePlayoutMonitor,
            },
        },
    },
    ingest: {
        id: 3,

        key: "ingest",
        label: "Ingest",
        permission: "",
        active: activeNavTabState("ingest"),
        disabled: true,
        tabs: {
            ingestManageRecording: {
                active: activeNavTabState("ingestManageRecording"),
                disabled: true,
                permission: "",
                link: "",
                key: "ingestManageRecording",
                label: EIngestNavAppList.ingestManageRecording,
            },
            ingestCreateRecording: {
                active: activeNavTabState("ingestCreateRecording"),
                disabled: true,
                permission: "",
                link: "",
                key: "ingestCreateRecording",
                label: EIngestNavAppList.ingestCreateRecording,
            },
        },
    },
    mam: {
        id: 4,

        key: "mam",
        label: "MAM",
        permission: "",
        active: activeNavTabState("mam"),
        disabled: true,
        tabs: {
            mamManageUserStorage: {
                active: activeNavTabState("mamManageUserStorage"),
                disabled: true,
                permission: "",
                link: "",
                key: "mamManageUserStorage",
                label: EMamNavAppList.mamManageUserStorage,
            },
            mamCreateUserStorage: {
                active: activeNavTabState("mamCreateUserStorage"),
                disabled: true,
                permission: "",
                link: "",
                key: "mamCreateUserStorage",
                label: EMamNavAppList.mamCreateUserStorage,
            },
        },
    },
    fastSync: {
        id: 5,

        key: "fastSync",
        label: "Fast Sync",
        active: activeNavTabState("fastSync"),
        disabled: true,
        permission: "",
        tabs: {
            fastSyncManageFastSync: {
                active: activeNavTabState("fastSyncManageFastSync"),
                disabled: true,
                permission: "",
                link: "",
                key: "fastSyncManageFastSync",
                label: EFastSyncNavAppList.fastSyncManageFastSync,
            },
            fastSyncCreateFastSync: {
                active: activeNavTabState("fastSyncCreateFastSync"),
                disabled: true,
                permission: "",
                link: "",
                key: "fastSyncCreateFastSync",
                label: EFastSyncNavAppList.fastSyncCreateFastSync,
            },
        },
    },
    adReplacer: {
        id: 6,

        key: "adReplacer",
        label: "Ad replacer",
        permission: "",
        active: activeNavTabState("adReplacer"),
        disabled: true,
        tabs: {
            adReplacerManageAdReplacer: {
                active: activeNavTabState("adReplacerManageAdReplacer"),
                disabled: true,
                permission: "",
                link: "",
                key: "adReplacerManageAdReplacer",
                label: EAdReplacerNavAppList.adReplacerManageAdReplacer,
            },
        },
    },
};
