import {EIpMonitoringNavAppList, ENextomonQaNavAppList, INavMonitoringState} from "./types";
import {activeNavTabState} from "../utils";

export const monitoringInitialState: INavMonitoringState = {
    ipMonitoring: {
        id: 1,
        key: "ipMonitoring",
        label: "IP Monitoring",
        permission: "",
        active: activeNavTabState("ipMonitoring"),
        disabled: true,
        tabs: {
            ipMonitoringBatchMonitoring: {
                id: 6,
                active: activeNavTabState("ipMonitoringBatchMonitoring"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringBatchMonitoring",
                label: EIpMonitoringNavAppList.ipMonitoringBatchMonitoring,
            },
            ipMonitoringCreateIPMonitoring: {
                id: 2,
                active: activeNavTabState("ipMonitoringCreateIPMonitoring"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringCreateIPMonitoring",
                label: EIpMonitoringNavAppList.ipMonitoringCreateIPMonitoring,
            },
            ipMonitoringHiddenErrors: {
                id: 5,
                active: activeNavTabState("ipMonitoringHiddenErrors"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringHiddenErrors",
                label: EIpMonitoringNavAppList.ipMonitoringHiddenErrors,
            },
            ipMonitoringLiveMonitor: {
                id: 4,
                active: activeNavTabState("ipMonitoringLiveMonitor"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringLiveMonitor",
                label: EIpMonitoringNavAppList.ipMonitoringLiveMonitor,
            },
            ipMonitoringManageMonitoring: {
                id: 1,
                active: activeNavTabState("ipMonitoringManageMonitoring"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringManageMonitoring",
                label: EIpMonitoringNavAppList.ipMonitoringManageMonitoring,
            },
            ipMonitoringManagePresets: {
                id: 3,
                active: activeNavTabState("ipMonitoringManagePresets"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringManagePresets",
                label: EIpMonitoringNavAppList.ipMonitoringManagePresets,
            },
            ipMonitoringServerRoomMonitoring: {
                id: 7,
                active: activeNavTabState("ipMonitoringServerRoomMonitoring"),
                disabled: true,
                permission: "",
                link: "",
                key: "ipMonitoringServerRoomMonitoring",
                label: EIpMonitoringNavAppList.ipMonitoringServerRoomMonitoring,
            },
        },
    },
    nextomonQa: {
        id: 2,
        key: "nextomonQa",
        label: "Nextomon QA",
        active: activeNavTabState("nextomonQa"),
        disabled: true,
        permission: "",
        tabs: {
            apMonitoringQa: {
                active: activeNavTabState("apMonitoringQa"),
                disabled: true,
                permission: "",
                link: "",
                key: "apMonitoringQa",
                label: ENextomonQaNavAppList.apMonitoringQa,
            },
        },
    },
};
